services:
  zoomrec_client:
    build:
      args:
        GPU_BUILD: VAAPI
        GPU_BUILD_SUBTYPE: INTEL
        RENDER_GROUPID: ${RENDER_GROUPID}
    environment:
      FFMPEG_INPUT_PARAMS: "-vaapi_device /dev/dri/renderD128"
      FFMPEG_OUTPUT_PARAMS: "-acodec aac -b:a 128k -vf 'hwupload,scale_vaapi=format=nv12' -c:v hevc_vaapi -b:v 1M"
      LIBVA_DRIVER_NAME: ${LIBVA_DRIVER_NAME}
    devices:
      - "/dev/dri:/dev/dri"
    group_add:
      - "${VIDEO_GROUPID}"
      - "${RENDER_GROUPID}"
