services:
  zoomrec_server:
    container_name: zoomrec_server
    image: rkilchmn/zoomrec_server:latest
    build:
      context: .
      dockerfile: server/res/Dockerfile
      args:
        ZOOMREC_USER_ID: ${ZOOMREC_USER_ID}
        ZOOMREC_USER_GID: ${ZOOMREC_USER_GID}
    restart: unless-stopped
    env_file:
      - ${ZOOMREC_HOME}/.server.env
    environment:
      - $ZOOMREC_HOME=${ZOOMREC_HOME}
      - ZOOMREC_USER_ID=${ZOOMREC_USER_ID}
      - ZOOMREC_USER_GID=${ZOOMREC_USER_GID}
      - SERVER_PORT=${SERVER_PORT}
      - SSH_PORT=${SSH_PORT}
    volumes:
      - ${ZOOMREC_HOME}/data:/home/zoomrec/data
      - ${ZOOMREC_HOME}/config:/home/zoomrec/config
      - ${ZOOMREC_HOME}/data/sftp-data:/root/sftp-data
    ports:
      - "${SERVER_PORT_EXPOSED}:${SERVER_PORT}"
      - "${SSH_PORT_EXPOSED}:${SSH_PORT}"
    networks:
      - zoomrec-net

  zoomrec_client:
    container_name: zoomrec_client
    image: rkilchmn/zoomrec_client:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: client/res/Dockerfile
      args:
        ZOOMREC_USER_ID: ${ZOOMREC_USER_ID}
        ZOOMREC_USER_GID: ${ZOOMREC_USER_GID}
    env_file:
      - ${ZOOMREC_HOME}/.client.env
    environment:
      - $ZOOMREC_HOME=${ZOOMREC_HOME}
      - ZOOMREC_USER_ID=${ZOOMREC_USER_ID}
      - $ZOOMREC_USER_GID=${ZOOMREC_USER_GID}
      - SERVER_URL=${SERVER_URL}
      - SSH_SERVER_URL=${SSH_SERVER_URL}
      - WHISPER_API_URL=${WHISPER_API_URL}
      - SAMBA_USERNAME=${SAMBA_USERNAME}
      - SAMBA_PASSWORD=${SAMBA_PASSWORD}
    volumes:
      - ${ZOOMREC_HOME}/data:/home/zoomrec/data
      - ${ZOOMREC_HOME}/config:/home/zoomrec/config
    ports:
      - "5901:5901"
      - "445:445"
      - "137-138:137-138"
    security_opt:
      - seccomp:unconfined
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - zoomrec-net

  remote-faster-whisper:
    image: rkilchmn/remote-faster-whisper:latest
    container_name: remote-faster-whisper
    restart: unless-stopped
    ports:
      - "9876:9876"
    volumes:
      - ${ZOOMREC_HOME}/whisper-cache:/app/whisper-cache
    networks:
      - zoomrec-net

networks:
  zoomrec-net:
    driver: bridge
